import {describe, expect, test} from 'bun:test';
import {
	attributionViolation,
	commitMessagesFromArgs,
	commitMessagesFromCommand,
	gitCommitMessagesViolation,
	ghPrMessagesViolation,
} from './commit-guard';
import {executeTool} from './tools';

const toolCall = (
	name: string,
	args: Record<string, unknown>,
): {
	id: string;
	name: string;
	arguments: Record<string, unknown>;
	rawArguments: string;
} => ({
	id: 'call-1',
	name,
	arguments: args,
	rawArguments: JSON.stringify(args),
});

describe('attributionViolation (no AI credit in commit/PR messages)', () => {
	test('flags Co-authored-by and Generated by variants', () => {
		expect(
			attributionViolation('fix: x\n\nCo-authored-by: Claude <c@x>'),
		).not.toBeNull();
		expect(attributionViolation('Generated by Claude')).not.toBeNull();
		expect(attributionViolation('generated with ChatGPT')).not.toBeNull();
		expect(attributionViolation('Authored by an AI assistant')).not.toBeNull();
		expect(attributionViolation('with the help of Copilot')).not.toBeNull();
	});

	test('case-insensitive', () => {
		expect(attributionViolation('co-authored-by: claude')).not.toBeNull();
		expect(attributionViolation('GENERATED BY: bobo')).not.toBeNull();
	});

	test('clean messages pass', () => {
		expect(attributionViolation('fix: typo in parser')).toBeNull();
		expect(
			attributionViolation('feat: add cache rate to status line'),
		).toBeNull();
	});
});

describe('commitMessagesFromArgs (git/gh CLI args)', () => {
	test('-m and --message forms', () => {
		expect(commitMessagesFromArgs(['-m', 'fix: x'])).toEqual(['fix: x']);
		expect(commitMessagesFromArgs(['--message=fix: y'])).toEqual(['fix: y']);
		expect(commitMessagesFromArgs(['-m', 'a', '-m', 'b'])).toEqual(['a', 'b']);
	});

	test('gh --title/--body forms', () => {
		expect(
			commitMessagesFromArgs(['--title', 'feat: x', '--body', 'details']),
		).toEqual(['feat: x', 'details']);
	});

	test('no message flags yields nothing', () => {
		expect(commitMessagesFromArgs(['--amend'])).toEqual([]);
	});
});

describe('commitMessagesFromCommand (bash command scan)', () => {
	test('extracts quoted and bare -m values', () => {
		expect(commitMessagesFromCommand('git commit -m "fix: x"')).toEqual([
			'fix: x',
		]);
		expect(commitMessagesFromCommand("git commit -m 'fix: y'")).toEqual([
			'fix: y',
		]);
		expect(commitMessagesFromCommand('git commit -m fix:z')).toEqual(['fix:z']);
		expect(commitMessagesFromCommand('git commit --message=fix:q')).toEqual([
			'fix:q',
		]);
	});

	test('extracts gh title/body values', () => {
		expect(
			commitMessagesFromCommand(
				'gh pr create --title "feat: x" --body "some body"',
			),
		).toEqual(['feat: x', 'some body']);
	});

	test('ignores commands without message flags', () => {
		expect(commitMessagesFromCommand('git add .')).toEqual([]);
		expect(commitMessagesFromCommand('git status')).toEqual([]);
	});
});

describe('gitCommitMessagesViolation (ONE single-line -m, no AI credit)', () => {
	test('a single clean line passes', () => {
		expect(gitCommitMessagesViolation(['fix: typo'])).toBeNull();
		expect(gitCommitMessagesViolation([])).toBeNull();
	});

	test('multiple -m flags are refused (multi-line body)', () => {
		expect(gitCommitMessagesViolation(['fix: x', 'body'])).not.toBeNull();
	});

	test('embedded newlines are refused', () => {
		expect(gitCommitMessagesViolation(['fix: x\n\nlong body'])).not.toBeNull();
	});

	test('AI attribution is refused', () => {
		expect(
			gitCommitMessagesViolation(['fix: x\n\nCo-authored-by: Claude <c@x>']),
		).not.toBeNull();
	});
});

describe('ghPrMessagesViolation (no AI credit; multi-line bodies are fine)', () => {
	test('title + body pass', () => {
		expect(ghPrMessagesViolation(['feat: x', 'A real body'])).toBeNull();
		expect(ghPrMessagesViolation([])).toBeNull();
	});

	test('LLM credit is refused', () => {
		expect(
			ghPrMessagesViolation(['feat: x', 'Generated by Claude']),
		).not.toBeNull();
	});
});

describe('executeTool refusal (git/gh rules enforced BEFORE running)', () => {
	test('execute_bash refuses a git commit with AI attribution', async () => {
		const result = await executeTool(
			toolCall('execute_bash', {
				command: 'git commit -m "fix: x\n\nCo-authored-by: Claude <c@x>"',
			}),
		);
		expect(result.content).toContain('REFUSED');
		expect(result.content).toContain('AI-attribution');
	});

	test('execute_bash refuses multiple -m flags (multi-line body)', async () => {
		const result = await executeTool(
			toolCall('execute_bash', {
				command: 'git commit -m "fix: x" -m "body paragraph"',
			}),
		);
		expect(result.content).toContain('REFUSED');
	});

	test('execute_bash refuses a multi-line -m', async () => {
		const result = await executeTool(
			toolCall('execute_bash', {
				command: 'git commit -m "fix: x\n\nlong body"',
			}),
		);
		expect(result.content).toContain('REFUSED');
	});

	test('execute_bash refuses gh pr create that credits an LLM', async () => {
		const result = await executeTool(
			toolCall('execute_bash', {
				command: 'gh pr create --title "feat: x" --body "Generated by Claude"',
			}),
		);
		expect(result.content).toContain('REFUSED');
	});

	test('clean git commands still run (guard is not a blanket block)', async () => {
		const result = await executeTool(
			toolCall('execute_bash', {command: 'git status --short'}),
		);
		expect(result.content).not.toContain('REFUSED');
		expect(result.content).toContain('EXIT_CODE');
	});
});
