/**
 * House rules for messages the agent writes to git/gh: a `git commit`
 * message is exactly ONE line and carries NO AI-attribution line, and a
 * `gh pr create` body never credits an LLM ("Generated by:", "Co-authored
 * by:", …). These are pure validators shared by the `execute_bash` and
 * git commands routed through `execute_bash`, so a bad message is refused before it lands.
 */

/** Attribution phrases that must never appear in a commit/PR message. */
const AI_ATTRIBUTION_RE =
	/\b(?:co-authored-by|generated by|authored by|written by|created by|assisted by|powered by|generated with|with the help of|in collaboration with)\b[:\s]/i;

/** Why a single message string violates the no-AI-credit rule, or null. */
export function attributionViolation(message: string): string | null {
	return AI_ATTRIBUTION_RE.test(message)
		? 'AI-attribution lines (Co-authored-by: / Generated by: / similar LLM credit) are not allowed'
		: null;
}

/**
 * Extract the message values from raw git/gh CLI arguments
 * (`-m x`, `-m "x"`, `--message=x`, `--body`, `--title`, …).
 * Pure, unit-tested.
 */
export function commitMessagesFromArgs(args: string[]): string[] {
	const messages: string[] = [];
	const valueFlags = new Set(['-m', '--message', '-b', '--body', '--title']);
	for (let i = 0; i < args.length; i++) {
		const arg = args[i]!;
		if (valueFlags.has(arg)) {
			const value = args[i + 1];
			if (value !== undefined) messages.push(value);
			i += 1;
		} else if (
			arg.startsWith('--message=') ||
			arg.startsWith('--body=') ||
			arg.startsWith('--title=')
		) {
			messages.push(arg.slice(arg.indexOf('=') + 1));
		}
	}
	return messages;
}

/**
 * Extract the message values a BASH COMMAND passes to `git commit` /
 * `gh pr create` (quoted or bare, `-m value`, `--body=value`, …).
 * Pure, unit-tested.
 */
export function commitMessagesFromCommand(command: string): string[] {
	const messages: string[] = [];
	const re =
		/(?:^|\s)(?:-m|--message|-b|--body|--title)(?:\s*=\s*|\s+)(?:"([^"]*)"|'([^']*)'|(\S+))/gi;
	for (const match of command.matchAll(re)) {
		const value = match[1] ?? match[2] ?? match[3];
		if (value) messages.push(value);
	}
	return messages;
}

/**
 * Validate a `git commit` invocation: exactly ONE message flag, single
 * line, no AI attribution. Returns the violation or null.
 * Pure, unit-tested.
 */
export function gitCommitMessagesViolation(messages: string[]): string | null {
	if (messages.length > 1) {
		return 'git commit accepts exactly ONE -m message (multiple flags produce a multi-line body)';
	}
	for (const message of messages) {
		const attribution = attributionViolation(message);
		if (attribution) return attribution;
		if (message.includes('\n')) {
			return 'git commit message must be a SINGLE line (no body paragraphs)';
		}
	}
	return null;
}

/**
 * Validate a `gh pr create` invocation: no AI attribution in the title or
 * body (PR bodies may legitimately be multi-line). Returns the violation or
 * null. Pure, unit-tested.
 */
export function ghPrMessagesViolation(messages: string[]): string | null {
	for (const message of messages) {
		const attribution = attributionViolation(message);
		if (attribution) return attribution;
	}
	return null;
}
